language: go
go_import_path: github.com/projectcontour/gimbal
go:
  - 1.14.x

sudo: false

cache:
  directories:
    - /home/travis/.cache/go-build
    - /home/travis/gopath/pkg/mod

env:
  - GOPROXY=https://proxy.golang.org/

script:
  - make check